### ISSUE TITLE
Need to display the percentage of filled employee details in employee profile

### ISSUE THREAD

**Issue by subhashkommina** [eshwarnadh/flairtech-vs#708]
As per the requirement,
we need to display the percentage of employee profile filled by the employee.
Need to show the percentage (img/button/any) after the org chart button.
Total 5 sections in employee,(each section carries 20%)  the threshold to apply any letter requests of the employee is around 80%
if the percentage is less we need to suggest the employee to complete the profile..

**Comment by Sriram-52** [comment]
Duplicate issue - 691
