### ISSUE TITLE
#83 Deployment Failed

### ISSUE THREAD

**Issue by FarookhSyed** [eshwarnadh/flairtech-vs#725]
**Log Report**

.\src\pages\EmployeeProfilePage.js
Cannot find file '../components/Employee/MenuBar' in '.\src\pages'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! veridicsolutions@0.1.0 build: `react-scripts --max_old_space_size=5096 build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the veridicsolutions@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_logs\2020-05-27T16_02_32_296Z-debug.log

**Comment by Sriram-52** [comment]
Due to new Menu Bar which hasn't committed into branch the issue occurs 
I created a pull request for that hope the problem solves
